import React, { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { Search, Loader2, Save, Printer, ShieldCheck, AlertCircle, Users, BedDouble, Calendar, CreditCard, ChevronRight, QrCode } from 'lucide-react';
import api from '../../services/api';
import QRScannerModal from '../../components/ui/QRScannerModal';

export default function GHCoordinatorDashboard() {
    const { user } = useAuth();
    const [bookings, setBookings] = useState([]);
    const [loading, setLoading] = useState(true);
    const [searchId, setSearchId] = useState('');
    const [selectedBooking, setSelectedBooking] = useState(null);
    const [loadingDetails, setLoadingDetails] = useState(false);
    const [isQRScannerOpen, setIsQRScannerOpen] = useState(false);

    // Override State
    const [overridePayload, setOverridePayload] = useState(null);
    const [saving, setSaving] = useState(false);

    useEffect(() => {
        fetchModifiableBookings();
    }, []);

    const fetchModifiableBookings = async () => {
        setLoading(true);
        try {
            const res = await api.get('/coordinator/bookings');
            setBookings(res.data?.data || []);
        } catch (error) {
            console.error("Failed to fetch coordinator bookings:", error);
        } finally {
            setLoading(false);
        }
    };

    const fetchBookingDetails = async (id) => {
        setLoadingDetails(true);
        try {
            const res = await api.get(`/coordinator/bookings/${id}`);
            setSelectedBooking(res.data.data);
            setOverridePayload({
                newRoomType: res.data.data.room_type,
                newArrival: res.data.data.arrival_datetime,
                newDeparture: res.data.data.departure_datetime,
                newTotalAmount: res.data.data.total_estimated_amount,
                overrideReason: '',
                guestsToUpdate: res.data.data.guests.map(g => ({
                    guest_id: g.guest_id,
                    departure_datetime: g.departure_datetime,
                    preferred_occupancy: g.preferred_occupancy,
                    preferred_extra_bed: g.preferred_extra_bed
                }))
            });
        } catch (error) {
            alert('Failed to load booking details.');
        } finally {
            setLoadingDetails(false);
        }
    };

    const handleSearch = (e) => {
        e.preventDefault();
        if (!searchId.trim()) return;
        const found = bookings.find(b => b.booking_id.includes(searchId) || b.booking_id.split('-')[0].includes(searchId));
        if (found) {
            fetchBookingDetails(found.booking_id);
        } else {
            // Attempt direct fetch
            fetchBookingDetails(searchId);
        }
    };

    const handleOverrideSubmit = async () => {
        if (!overridePayload.overrideReason) {
            return alert('Please provide a reason for this override.');
        }
        setSaving(true);
        try {
            await api.put(`/coordinator/bookings/${selectedBooking.booking_id}/override`, overridePayload);
            alert('Booking successfully overridden.');
            fetchBookingDetails(selectedBooking.booking_id); // reload
        } catch (error) {
            alert('Failed to apply override.');
        } finally {
            setSaving(false);
        }
    };

    const handleGenerateFinalBill = async () => {
        if (!window.confirm("Are you sure? This will lock the bill and send it to Reception.")) return;
        setSaving(true);
        try {
            const billData = {
                subtotal: overridePayload.newTotalAmount * 0.88,
                gst: overridePayload.newTotalAmount * 0.12,
                total: overridePayload.newTotalAmount,
                generated_json: { notes: "Generated by Coordinator", items: [] }
            };
            await api.post(`/coordinator/bookings/${selectedBooking.booking_id}/generate-bill`, billData);
            alert('Final Bill Locked and Sent to Reception!');
            fetchBookingDetails(selectedBooking.booking_id); // reload
        } catch (error) {
            alert('Failed to generate bill.');
        } finally {
            setSaving(false);
        }
    };

    if (loading) {
        return (
            <div className="flex justify-center items-center h-64">
                <Loader2 className="w-8 h-8 animate-spin text-blue-600" />
            </div>
        );
    }

    return (
        <div className="space-y-6 max-w-7xl mx-auto pb-12 animate-fade-in">
            {/* Header */}
            <div className="bg-gradient-to-r from-slate-900 to-indigo-900 rounded-2xl p-8 text-white shadow-2xl relative overflow-hidden">
                <div className="absolute top-0 right-0 p-8 opacity-10">
                    <ShieldCheck className="w-32 h-32" />
                </div>
                <h1 className="text-3xl font-black mb-2 relative z-10 tracking-tight">GH Coordinator Command Center</h1>
                <p className="text-indigo-200 text-lg max-w-2xl relative z-10 font-medium">
                    Extreme manual overrides, bill locking, and operations management.
                </p>
            </div>

            <QRScannerModal 
                isOpen={isQRScannerOpen}
                onClose={() => setIsQRScannerOpen(false)}
                onScanSuccess={(decodedText) => {
                    setIsQRScannerOpen(false);
                    setSearchId(decodedText);
                    fetchBookingDetails(decodedText);
                }}
            />

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Left Column: Search & List */}
                <div className="lg:col-span-1 space-y-6">
                    <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-5">
                        <h2 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                            <Search className="w-5 h-5 text-indigo-500" /> Find Application
                        </h2>
                        <form onSubmit={handleSearch} className="flex gap-2">
                            <input
                                type="text"
                                placeholder="Enter App ID..."
                                className="flex-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl focus:ring-2 focus:ring-indigo-500 outline-none transition-all font-medium text-slate-700"
                                value={searchId}
                                onChange={(e) => setSearchId(e.target.value)}
                            />
                            <button type="submit" className="bg-indigo-600 text-white px-4 py-2 rounded-xl font-bold hover:bg-indigo-700 transition-colors shadow-md">
                                Load
                            </button>
                            <button 
                                type="button" 
                                onClick={() => setIsQRScannerOpen(true)}
                                className="bg-slate-800 text-white px-4 py-2 rounded-xl font-bold hover:bg-slate-900 transition-colors shadow-md flex items-center justify-center shrink-0"
                                title="Scan Application QR Pass"
                            >
                                <QrCode className="w-5 h-5" />
                            </button>
                        </form>
                    </div>

                    <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-5 h-[600px] flex flex-col">
                        <h2 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                            <AlertCircle className="w-5 h-5 text-amber-500" /> Active Operations ({bookings.length})
                        </h2>
                        <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar space-y-2">
                            {bookings.map(b => (
                                <div 
                                    key={b.booking_id}
                                    onClick={() => fetchBookingDetails(b.booking_id)}
                                    className={`p-3 rounded-xl border cursor-pointer transition-all ${selectedBooking?.booking_id === b.booking_id ? 'bg-indigo-50 border-indigo-300 ring-1 ring-indigo-200' : 'bg-slate-50 border-slate-100 hover:border-indigo-200 hover:bg-white'}`}
                                >
                                    <div className="flex justify-between items-start mb-1">
                                        <span className="font-bold text-sm text-slate-800">{b.booking_id.split('-')[0].toUpperCase()}</span>
                                        <span className={`text-[9px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${b.booking_state === 'CHECKED_IN' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
                                            {b.booking_state}
                                        </span>
                                    </div>
                                    <p className="text-xs text-slate-600 font-medium truncate">{b.applicant_name}</p>
                                    <p className="text-[10px] text-slate-500 mt-1">{new Date(b.arrival_datetime).toLocaleDateString()} - {b.rooms_required} Room(s)</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                {/* Right Column: Override UI */}
                <div className="lg:col-span-2">
                    {loadingDetails ? (
                        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-12 flex flex-col items-center justify-center h-full">
                            <Loader2 className="w-10 h-10 animate-spin text-indigo-500 mb-4" />
                            <p className="text-slate-500 font-medium">Extracting application data...</p>
                        </div>
                    ) : selectedBooking && overridePayload ? (
                        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 flex flex-col h-full animate-fade-in">
                            <div className="p-6 border-b border-slate-100 flex justify-between items-center bg-slate-50/50 rounded-t-2xl">
                                <div>
                                    <h2 className="text-2xl font-black text-slate-800 mb-1 flex items-center gap-3">
                                        App {selectedBooking.booking_id.split('-')[0].toUpperCase()}
                                        {selectedBooking.final_bill && (
                                            <span className="text-xs bg-emerald-100 text-emerald-800 px-2 py-1 rounded-md border border-emerald-200 flex items-center gap-1 shadow-sm">
                                                <ShieldCheck className="w-3 h-3" /> BILL LOCKED
                                            </span>
                                        )}
                                    </h2>
                                    <p className="text-sm font-bold text-slate-500">{selectedBooking.applicant_name} ({selectedBooking.applicant_email})</p>
                                </div>
                                <div className="text-right">
                                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">Current Status</p>
                                    <p className="text-sm font-bold text-indigo-600 bg-indigo-50 px-3 py-1 rounded-lg border border-indigo-100">{selectedBooking.booking_state}</p>
                                </div>
                            </div>

                            <div className="p-6 space-y-8 flex-1 overflow-y-auto">
                                {/* Global Overrides */}
                                <div>
                                    <h3 className="text-sm font-black text-slate-800 uppercase tracking-widest mb-4 flex items-center gap-2 pb-2 border-b border-slate-100">
                                        <Calendar className="w-4 h-4 text-indigo-500" /> Global Override Settings
                                    </h3>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div>
                                            <label className="block text-xs font-bold text-slate-600 mb-1">Room Category / Type</label>
                                            <select 
                                                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm font-medium outline-none focus:ring-2 focus:ring-indigo-500"
                                                value={overridePayload.newRoomType}
                                                onChange={(e) => setOverridePayload({...overridePayload, newRoomType: e.target.value})}
                                            >
                                                <option value="Standard Room">Standard Room</option>
                                                <option value="Mini Suite Room">Mini Suite Room</option>
                                                <option value="Suite Room">Suite Room</option>
                                            </select>
                                        </div>
                                        <div>
                                            <label className="block text-xs font-bold text-slate-600 mb-1">Total Estimated Amount (₹)</label>
                                            <input 
                                                type="number"
                                                className="w-full bg-slate-50 border border-slate-200 rounded-xl px-3 py-2 text-sm font-bold text-indigo-700 outline-none focus:ring-2 focus:ring-indigo-500"
                                                value={overridePayload.newTotalAmount}
                                                onChange={(e) => setOverridePayload({...overridePayload, newTotalAmount: e.target.value})}
                                            />
                                        </div>
                                    </div>
                                </div>

                                {/* Guest Specific Overrides */}
                                <div>
                                    <h3 className="text-sm font-black text-slate-800 uppercase tracking-widest mb-4 flex items-center gap-2 pb-2 border-b border-slate-100">
                                        <Users className="w-4 h-4 text-indigo-500" /> Guest Stay Operations
                                    </h3>
                                    <div className="space-y-3">
                                        {overridePayload.guestsToUpdate.map((gPayload, idx) => {
                                            const originalGuest = selectedBooking.guests.find(g => g.guest_id === gPayload.guest_id);
                                            return (
                                                <div key={gPayload.guest_id} className="bg-white border border-slate-200 rounded-xl p-4 shadow-sm hover:shadow-md transition-shadow">
                                                    <div className="flex justify-between items-center mb-3">
                                                        <span className="font-bold text-sm text-slate-800">{originalGuest.guest_name}</span>
                                                        <span className="text-xs text-slate-500 bg-slate-100 px-2 py-0.5 rounded font-medium">{originalGuest.relation_to_applicant}</span>
                                                    </div>
                                                    <div className="grid grid-cols-3 gap-3">
                                                        <div>
                                                            <label className="block text-[10px] font-bold text-slate-500 mb-1 uppercase">Occupancy</label>
                                                            <select 
                                                                className="w-full bg-slate-50 border border-slate-200 rounded-lg px-2 py-1.5 text-xs font-medium outline-none"
                                                                value={gPayload.preferred_occupancy}
                                                                onChange={(e) => {
                                                                    const newArr = [...overridePayload.guestsToUpdate];
                                                                    newArr[idx].preferred_occupancy = e.target.value;
                                                                    setOverridePayload({...overridePayload, guestsToUpdate: newArr});
                                                                }}
                                                            >
                                                                <option value="single">Single</option>
                                                                <option value="double">Double</option>
                                                            </select>
                                                        </div>
                                                        <div>
                                                            <label className="block text-[10px] font-bold text-slate-500 mb-1 uppercase">Checkout Date</label>
                                                            <input 
                                                                type="datetime-local"
                                                                className="w-full bg-slate-50 border border-slate-200 rounded-lg px-2 py-1.5 text-[11px] font-medium outline-none"
                                                                value={new Date(gPayload.departure_datetime).toISOString().slice(0, 16)}
                                                                onChange={(e) => {
                                                                    const newArr = [...overridePayload.guestsToUpdate];
                                                                    newArr[idx].departure_datetime = new Date(e.target.value).toISOString();
                                                                    setOverridePayload({...overridePayload, guestsToUpdate: newArr});
                                                                }}
                                                            />
                                                        </div>
                                                        <div className="flex items-end pb-1">
                                                            <label className="flex items-center gap-2 cursor-pointer">
                                                                <input 
                                                                    type="checkbox"
                                                                    className="rounded border-slate-300 text-indigo-600 focus:ring-indigo-500"
                                                                    checked={gPayload.preferred_extra_bed}
                                                                    onChange={(e) => {
                                                                        const newArr = [...overridePayload.guestsToUpdate];
                                                                        newArr[idx].preferred_extra_bed = e.target.checked;
                                                                        setOverridePayload({...overridePayload, guestsToUpdate: newArr});
                                                                    }}
                                                                />
                                                                <span className="text-xs font-bold text-slate-600">Extra Bed (+₹400)</span>
                                                            </label>
                                                        </div>
                                                    </div>
                                                </div>
                                            );
                                        })}
                                    </div>
                                </div>

                                {/* Security Justification */}
                                <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
                                    <label className="block text-xs font-black text-amber-800 uppercase tracking-widest mb-2 flex items-center gap-1">
                                        <AlertCircle className="w-3 h-3" /> Mandatory Override Reason (Audit Log)
                                    </label>
                                    <textarea 
                                        rows="2"
                                        placeholder="Explain why these rates or details were manually altered..."
                                        className="w-full bg-white border border-amber-200 rounded-lg px-3 py-2 text-sm font-medium outline-none focus:ring-2 focus:ring-amber-500 placeholder:text-amber-300 text-amber-900"
                                        value={overridePayload.overrideReason}
                                        onChange={(e) => setOverridePayload({...overridePayload, overrideReason: e.target.value})}
                                    ></textarea>
                                </div>
                            </div>

                            <div className="p-6 border-t border-slate-100 bg-slate-50 rounded-b-2xl flex justify-between items-center">
                                <button 
                                    onClick={handleOverrideSubmit}
                                    disabled={saving || !overridePayload.overrideReason}
                                    className="px-6 py-2.5 bg-slate-800 text-white rounded-xl font-bold text-sm shadow-md hover:bg-slate-900 hover:shadow-lg transition-all disabled:opacity-50 flex items-center gap-2"
                                >
                                    {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Save className="w-4 h-4" />}
                                    Save Override Changes
                                </button>

                                <button 
                                    onClick={handleGenerateFinalBill}
                                    disabled={saving || selectedBooking.final_bill}
                                    className="px-6 py-2.5 bg-gradient-to-r from-emerald-500 to-emerald-600 text-white rounded-xl font-bold text-sm shadow-md shadow-emerald-200 hover:shadow-lg hover:from-emerald-600 hover:to-emerald-700 transition-all disabled:opacity-50 flex items-center gap-2"
                                >
                                    {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Printer className="w-4 h-4" />}
                                    {selectedBooking.final_bill ? 'Bill Already Locked' : 'Lock Bill & Send to Reception'}
                                </button>
                            </div>
                        </div>
                    ) : (
                        <div className="bg-slate-50 rounded-2xl border border-slate-200 border-dashed flex flex-col items-center justify-center h-full text-slate-400 p-12 text-center">
                            <ShieldCheck className="w-16 h-16 mb-4 opacity-50" />
                            <h3 className="text-xl font-bold text-slate-600 mb-2">No Application Selected</h3>
                            <p className="text-sm">Search for an application ID or select one from the list to begin overriding operations.</p>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
