exports.ROLES = {
    STUDENT: 'student',
    FACULTY: 'faculty',
    HOD: 'hod',
    DEAN: 'dean',
    REGISTRAR: 'registrar',
    GUEST_HOUSE_ADMIN: 'guest_house_admin',
    RECEPTIONIST: 'reception_staff',
    DIRECTOR: 'director',
    GH_COORDINATOR: 'gh_coordinator',
    STAFF: 'staff'
};

exports.BOOKING_STATUS = {
    DRAFT: 'DRAFT',
    PENDING_APPROVER: 'PENDING_APPROVER',
    PENDING_DIRECTOR: 'PENDING_DIRECTOR',
    DIRECTOR_REJECTED: 'DIRECTOR_REJECTED',
    APPROVER_APPROVED: 'APPROVER_APPROVED',
    APPROVER_REJECTED: 'APPROVER_REJECTED',
    PENDING_ADMIN: 'PENDING_ADMIN',
    ADMIN_APPROVED: 'ADMIN_APPROVED',
    ADMIN_REJECTED: 'ADMIN_REJECTED',
    READY_FOR_CHECKIN: 'READY_FOR_CHECKIN',
    CHECKED_IN: 'CHECKED_IN',
    CHECKED_OUT: 'CHECKED_OUT',
    NO_SHOW: 'NO_SHOW',
    CANCELLED: 'CANCELLED'
};

exports.PAYMENT_STATUS = {
    NOT_APPLICABLE: 'NOT_APPLICABLE',
    PENDING: 'PENDING',
    PROOF_SUBMITTED: 'PAYMENT_PROOF_SUBMITTED',
    PROOF_RESUBMITTED: 'PAYMENT_PROOF_RESUBMITTED',
    UNDER_REVIEW: 'UNDER_REVIEW',
    PAID: 'PAID',
    REJECTED: 'REJECTED',
    WARNING_1_SENT: 'WARNING_1_SENT',
    WARNING_2_SENT: 'WARNING_2_SENT',
    WARNING_3_SENT: 'WARNING_3_SENT',
    FAILED: 'FAILED',
    REFUND_INITIATED: 'REFUND_INITIATED',
    REFUNDED: 'REFUNDED'
};