export const ROLES = {
  STUDENT: 'student',
  FACULTY: 'faculty',
  HOD: 'hod',
  DEAN: 'dean',
  REGISTRAR: 'registrar',
  ADMIN: 'super_admin',
  GUEST_HOUSE_ADMIN: 'guest_house_admin',
  RECEPTIONIST: 'reception_staff',
  DIRECTOR: 'director',
  GH_COORDINATOR: 'gh_coordinator',
  STAFF: 'staff',
};

export const BOOKING_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVER: 'PENDING_APPROVER',
  PENDING_DIRECTOR: 'PENDING_DIRECTOR',
  DIRECTOR_REJECTED: 'DIRECTOR_REJECTED',
  APPROVER_APPROVED: 'APPROVER_APPROVED',
  APPROVER_REJECTED: 'APPROVER_REJECTED',
  PENDING_ADMIN: 'PENDING_ADMIN',
  ADMIN_APPROVED: 'ADMIN_APPROVED',
  ADMIN_REJECTED: 'ADMIN_REJECTED',
  READY_FOR_CHECKIN: 'READY_FOR_CHECKIN',
  CHECKED_IN: 'CHECKED_IN',
  CHECKED_OUT: 'CHECKED_OUT',
  NO_SHOW: 'NO_SHOW',
  CANCELLED: 'CANCELLED',
};

export const BOOKING_TYPES = {
  NORMAL: 'NORMAL',
  BULK_BOOKING: 'BULK_BOOKING',
};

export const BULK_BOOKING_STATUS_LABELS = {
  [BOOKING_STATUS.DRAFT]: 'Draft',
  [BOOKING_STATUS.PENDING_APPROVER]: 'Pending Approving Authority',
  [BOOKING_STATUS.PENDING_DIRECTOR]: 'Pending Director',
  [BOOKING_STATUS.APPROVER_REJECTED]: 'Rejected by Authority',
  [BOOKING_STATUS.DIRECTOR_REJECTED]: 'Rejected by Director',
  [BOOKING_STATUS.PENDING_ADMIN]: 'Pending Guest House Chair',
  [BOOKING_STATUS.ADMIN_APPROVED]: 'Confirmed',
  [BOOKING_STATUS.ADMIN_REJECTED]: 'Rejected by GHC',
  [BOOKING_STATUS.CHECKED_IN]: 'Active',
  [BOOKING_STATUS.CHECKED_OUT]: 'Completed',
  [BOOKING_STATUS.CANCELLED]: 'Cancelled',
};
